### ISSUE TITLE
Google Docs issue

### ISSUE THREAD

**Issue by Magicie** [sfarbota/toggl-button-for-custom-websites#3]
There are multiple "start timer" buttons in Google Docs. This is causing the page to move (incl. rows  are displaced when you edit them).

![google docs - chrome](https://cloud.githubusercontent.com/assets/8112552/6411910/9dafc962-be7d-11e4-9972-fb0383e41af1.png)

**Comment by sfarbota** [comment]
This should be resolved with the updated version of this extension (v0.6.8.1). Please feel free to reopen this issue if not!
