### ISSUE TITLE
Update from upstream

### ISSUE THREAD

**Issue by nafg** [sfarbota/toggl-button-for-custom-websites#4]
Hi, thanks a ton for this! Would you be able to pull updates from upstream and publish to the chrome web store?

It's not working on my youtrack instance, wondering if that would fix it.

**Comment by sfarbota** [comment]
Hi nafg! I (finally) just finished updating from upstream. Please update your plugin to version 0.6.8.1 and it should work now. If not, please feel free to open another issue!

And thanks for the kick in the butt to keep this up to date! It helps to know that people actually use it.
